server:
  port: 8080
spring:
  application:
    name: "ListenerMq"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
commons:
  jms:
    output-concurrency: 10
    output-queue: "DEV.QUEUE.2"
    input-queue: "DEV.QUEUE.1"
    producer-ttl: 60000
    reactive: true
    input-concurrency: 10
    input-queue-alias: ""
ibm:
  mq:
    channel: "DEV.APP.SVRCONN"
    user: "app"
    conn-name: "localhost(1414)"
    listener_timeout: 6000
    sender_timeout: 6000
    queue-manager: "QM1"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
